### PR TITLE
Add SDL_RaiseWindow

### PR DESCRIPTION
**Pull request by trolleyman**

### CODE REVIEW

**Comment by zaafar** [comment]
FYI: https://github.com/mellinoe/veldrid/issues/97

**Comment by trolleyman** [comment]
Right - so is the idea to only expose functions that are needed? I thought it might be cleaner for my code if all the SDL functions are in one place - i.e. in `Veldrid.SDL2`

**Comment by zaafar** [comment]
yeah, looks like that's the idea.

**Comment by mellinoe** [comment]
I don't have a problem with adding useful functions to Veldrid.SDL2, especially if they are windowing- or input-related.

**Pull request merged**
