### PR TITLE
Update veldrid.imagesharp code to use image sharp rc1

### PR DESCRIPTION
**Pull request by UkooLabs**
Updated code to use latest rc1 of imagesharp

### CODE REVIEW

**Comment by feliwir** [comment]
Would appreciate this getting merged quickly, since we're stuck with ImageSharp beta 6 currently when using Veldrid (last major release was on beta 6)

**Comment by mjkkirschner** [comment]
Isn't this version of imageSharp the first one to change the license to AGPL - which may complicate treating this repo as MIT licensed?

https://github.com/SixLabors/ImageSharp/blob/master/LICENSE

Or maybe this happened already in one of the previous beta versions?

**Comment by UkooLabs** [comment]
@mjkkirschner It should be fine as SixLabors said If you had an existing open source repo that used ImsgeSharp before it became RC you can continue to use InsgeSharp

**Comment by JimBobSquarePants** [comment]
@UkooLabs is correct. The readme states.

> Open Source projects who have taken a dependency on ImageSharp prior to adoption of the AGPL v3 license are permitted to use ImageSharp (including all future versions) under the previous Apache 2.0 License.

**Comment by JimBobSquarePants** [comment]
And like that... any ambiguity goes away 😄

**Pull request merged**
