### PR TITLE
Added Span<T> overloads

### PR DESCRIPTION
**Pull request by TechnologicalPizza**
Just a quality of life improvement.

### CODE REVIEW

**Comment by SimantoR** [comment]
Seems the .NET build fails due to myget feeds. Could you update it to fix those?

**Comment by TechnologicalPizza** [comment]
I updated and now it fails for some other weird reason...

**Comment by mellinoe** [comment]
Can you expand on when this would be useful? Wouldn't you be able to call the ReadOnlySpan in most cases since there is an implicit conversion?

**Comment by TechnologicalPizza** [comment]
The implicit conversion doesn't kick in because ReadOnlySpan is generic and the type is not being inferred.
I find this annoying because the XML doc has to be duplicated in source but it's annoying otherwise.

**Comment by mellinoe** [comment]
Got it. Yeah, after testing it, the generic nature of the method makes it so that it can't select the right overload. The only way to get it to work is to explicitly specify the type to `UpdateBuffer<T>` or to cast it manually. Neither is good. So this change looks correct to me.

**Pull request merged**
