### PR TITLE
[Metal] Fix mappings for SamplerDescription.AddressModeU/V/W.

### PR DESCRIPTION
**Pull request by tzachshabtay**
Reverting commit: https://github.com/mellinoe/veldrid/commit/be6d1db3d6d05344d35e0e0c57a8122a4305c395

See: https://github.com/mellinoe/veldrid/issues/176#issuecomment-503817730

### CODE REVIEW

**Comment by mellinoe** [comment]
I think the correct fix is to actually replicate that commit (rather than revert it) for the OpenGL backend. The [documentation for MTLSamplerDescriptor](https://developer.apple.com/documentation/metal/mtlsamplerdescriptor?language=objc) is pretty clear that S/T/R correspond to width/height/depth. This is definitely the case for OpenGL as well, although it's hard to find a good reference for it. The mappings in OpenGLSampler.cs are currently incorrect, as they were for Metal.

**Comment by tzachshabtay** [comment]
Ah, ok.
So the documentation in SamplerDescription probably needs to change as well.
For example:
https://github.com/mellinoe/veldrid/blob/80aa5db02df737c26f3e83e3ea7d662ac9892ce1/src/Veldrid/SamplerDescription.cs#L54

**Comment by mellinoe** [comment]
Yes, those descriptions are also inaccurate.

**Comment by mellinoe** [comment]
I made the change described above on the master branch, sot his shouldn't be needed. Let me know if you hit any issues after pulling that down.

**Pull request closed without merging**
